name: short_time_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: assets/icon/Logo_App.png

flutter:
  uses-material-design: true

  assets:
    - assets/food_pics/
    - assets/magazine_pics/
    - assets/profile_pics/
    - assets/sample_data/
    - assets/grocery_pics/
    - assets/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: assets\fonts\Inter\Inter-VariableFont_opsz,wght.ttf